/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/books": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Books */
        get: operations["get_books_api_books_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{isbn}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Book */
        get: operations["get_book_api_books__isbn__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/books/{isbn}/stock": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Stock */
        patch: operations["update_stock_api_books__isbn__stock_patch"];
        trace?: never;
    };
    "/api/customers/lookup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Lookup Customer */
        post: operations["lookup_customer_api_customers_lookup_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Register Customer */
        post: operations["register_customer_api_customers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/loyalty": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Loyalty */
        get: operations["get_loyalty_api_customers__customer_id__loyalty_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/rewards/redeem": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Redeem Reward */
        post: operations["redeem_reward_api_customers__customer_id__rewards_redeem_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/customers/{customer_id}/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Customer Orders */
        get: operations["get_customer_orders_api_customers__customer_id__orders_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Orders */
        get: operations["get_orders_api_orders_get"];
        put?: never;
        /** Create Order */
        post: operations["create_order_api_orders_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/orders/{order_id}/status": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update Order Status */
        patch: operations["update_order_status_api_orders__order_id__status_patch"];
        trace?: never;
    };
    "/api/orders/release-expired": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Force Release Expired */
        post: operations["force_release_expired_api_orders_release_expired_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Events */
        get: operations["get_events_api_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/store": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Store Info */
        get: operations["get_store_info_api_store_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/tree": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Chat Tree */
        get: operations["get_chat_tree_api_chat_tree_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/message": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Chat Message */
        post: operations["post_chat_message_api_chat_message_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/chat/escalate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Post Chat Escalate */
        post: operations["post_chat_escalate_api_chat_escalate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/messages": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Messages */
        get: operations["get_messages_api_messages_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketing/tones": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Tones */
        get: operations["get_tones_api_marketing_tones_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/marketing/generate": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate Marketing */
        post: operations["generate_marketing_api_marketing_generate_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Book
         * @description Domain model representing a book in the catalog and inventory.
         */
        Book: {
            /** Isbn */
            isbn: string;
            /** Title */
            title: string;
            /** Author */
            author: string;
            /** Format */
            format: string;
            /** Price Cents */
            price_cents: number;
            /** Stock Count */
            stock_count: number;
            /**
             * Reserved Count
             * @default 0
             */
            reserved_count: number;
            /**
             * Low Stock Threshold
             * @default 2
             */
            low_stock_threshold: number;
            /** Genre */
            genre: string;
            /**
             * Blurb
             * @default
             */
            blurb: string;
            /**
             * Cover Image Url
             * @default
             */
            cover_image_url: string;
            /** Publisher */
            publisher: string;
            /** Published Date */
            published_date: string;
            /**
             * Available Count
             * @description Derive currently available stock count (stock_count - reserved_count).
             */
            readonly available_count: number;
            /**
             * Stock Status
             * @description Compute stock status based on available count and low-stock threshold.
             */
            readonly stock_status: string;
        };
        /** ChatMessageRequest */
        ChatMessageRequest: {
            /** Node Id */
            node_id: string;
            /**
             * Input
             * @default
             */
            input: string | null;
        };
        /**
         * Customer
         * @description Domain model representing a bookstore customer and loyalty card.
         */
        Customer: {
            /** Customer Id */
            customer_id: string;
            /** Phone */
            phone: string;
            /** Name */
            name: string;
            /**
             * Email
             * @default
             */
            email: string;
            /**
             * Stamps
             * @default 0
             */
            stamps: number;
            /**
             * Rewards Available
             * @default 0
             */
            rewards_available: number;
            /** Joined Date */
            joined_date: string;
        };
        /** CustomerLookup */
        CustomerLookup: {
            /** Phone */
            phone: string;
        };
        /** CustomerRegister */
        CustomerRegister: {
            /** Phone */
            phone: string;
            /** Name */
            name: string;
            /**
             * Email
             * @default
             */
            email: string | null;
        };
        /** EscalateRequest */
        EscalateRequest: {
            /** Name */
            name: string;
            /** Contact */
            contact: string;
            /** Body */
            body: string;
        };
        /**
         * Event
         * @description Domain model representing a bookstore author or community event.
         */
        Event: {
            /** Event Id */
            event_id: string;
            /** Title */
            title: string;
            /** Author Name */
            author_name: string;
            /** Starts At */
            starts_at: string;
            /** Capacity */
            capacity: number;
            /**
             * Tickets Sold
             * @default 0
             */
            tickets_sold: number;
            /**
             * Description
             * @default
             */
            description: string;
        };
        /**
         * FAQItem
         * @description Domain model representing a FAQ question and answer pair.
         */
        FAQItem: {
            /** Id */
            id: string;
            /** Question */
            question: string;
            /** Keywords */
            keywords?: string[];
            /** Answer */
            answer: string;
        };
        /** GenerateRequest */
        GenerateRequest: {
            /** Subject Type */
            subject_type: string;
            /** Subject Id */
            subject_id: string;
            /** Tone */
            tone: string;
            /**
             * Variant
             * @default 0
             */
            variant: number | null;
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** LoyaltyResponse */
        LoyaltyResponse: {
            /** Stamps */
            stamps: number;
            /** Rewards Available */
            rewards_available: number;
            /** Stamps To Next Reward */
            stamps_to_next_reward: number;
        };
        /**
         * Message
         * @description Domain model representing a customer escalation message.
         */
        Message: {
            /** Message Id */
            message_id: string;
            /** Name */
            name: string;
            /** Contact */
            contact: string;
            /** Body */
            body: string;
            /** Created At */
            created_at: string;
            /**
             * Status
             * @default new
             */
            status: string;
        };
        /**
         * OperatingHours
         * @description Operating hours for a single day.
         */
        OperatingHours: {
            /** Open */
            open: string;
            /** Close */
            close: string;
        };
        /**
         * Order
         * @description Domain model representing a customer pre-order / hold reservation.
         */
        Order: {
            /** Order Id */
            order_id: string;
            /** Customer Id */
            customer_id: string;
            /** Items */
            items: components["schemas"]["OrderItem"][];
            /** Status */
            status: string;
            /** Created At */
            created_at: string;
            /** Hold Expires At */
            hold_expires_at: string;
            /** Total Cents */
            total_cents: number;
            /**
             * Notes
             * @default
             */
            notes: string;
        };
        /** OrderCreate */
        OrderCreate: {
            /** Customer Id */
            customer_id: string;
            /** Items */
            items: components["schemas"]["OrderItemInput"][];
            /**
             * Notes
             * @default
             */
            notes: string | null;
        };
        /**
         * OrderItem
         * @description Domain model representing a single line item in an order.
         */
        OrderItem: {
            /** Isbn */
            isbn: string;
            /**
             * Quantity
             * @default 1
             */
            quantity: number;
        };
        /** OrderItemInput */
        OrderItemInput: {
            /** Isbn */
            isbn: string;
            /** Quantity */
            quantity: number;
        };
        /** OrderStatusUpdate */
        OrderStatusUpdate: {
            /** Status */
            status: string;
        };
        /** ReleaseExpiredResponse */
        ReleaseExpiredResponse: {
            /** Released Count */
            released_count: number;
        };
        /** StockUpdate */
        StockUpdate: {
            /** Stock Count */
            stock_count: number;
        };
        /**
         * StoreHours
         * @description Store operating hours across the week.
         */
        StoreHours: {
            monday?: components["schemas"]["OperatingHours"] | null;
            tuesday?: components["schemas"]["OperatingHours"] | null;
            wednesday?: components["schemas"]["OperatingHours"] | null;
            thursday?: components["schemas"]["OperatingHours"] | null;
            friday?: components["schemas"]["OperatingHours"] | null;
            saturday?: components["schemas"]["OperatingHours"] | null;
            sunday?: components["schemas"]["OperatingHours"] | null;
        };
        /**
         * StoreInfo
         * @description Domain model representing bookstore metadata, hours, policies, and FAQs.
         */
        StoreInfo: {
            /** Name */
            name: string;
            /** Address */
            address: string;
            /** Phone */
            phone: string;
            /** Email */
            email: string;
            hours: components["schemas"]["StoreHours"];
            policies: components["schemas"]["StorePolicies"];
            /** Faqs */
            faqs?: components["schemas"]["FAQItem"][];
        };
        /**
         * StorePolicies
         * @description Store policies for customer and chatbot consumption.
         */
        StorePolicies: {
            /** Returns */
            returns: string;
            /** Holds */
            holds: string;
            /** Special Orders */
            special_orders: string;
            /** Gifts */
            gifts: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    get_books_api_books_get: {
        parameters: {
            query?: {
                q?: string | null;
                in_stock_only?: boolean;
                limit?: number | null;
                offset?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_book_api_books__isbn__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isbn: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_stock_api_books__isbn__stock_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                isbn: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StockUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Book"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    lookup_customer_api_customers_lookup_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerLookup"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    register_customer_api_customers_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CustomerRegister"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Customer"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_loyalty_api_customers__customer_id__loyalty_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoyaltyResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    redeem_reward_api_customers__customer_id__rewards_redeem_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_customer_orders_api_customers__customer_id__orders_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                customer_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_orders_api_orders_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    create_order_api_orders_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderCreate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    update_order_status_api_orders__order_id__status_patch: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                order_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["OrderStatusUpdate"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Order"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    force_release_expired_api_orders_release_expired_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ReleaseExpiredResponse"];
                };
            };
        };
    };
    get_events_api_events_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Event"][];
                };
            };
        };
    };
    get_store_info_api_store_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StoreInfo"];
                };
            };
        };
    };
    get_chat_tree_api_chat_tree_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    post_chat_message_api_chat_message_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ChatMessageRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    post_chat_escalate_api_chat_escalate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["EscalateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_messages_api_messages_get: {
        parameters: {
            query?: {
                status?: string | null;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Message"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_tones_api_marketing_tones_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
        };
    };
    generate_marketing_api_marketing_generate_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GenerateRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
